### ISSUE TITLE
Add database scheme creation and migrations in sequelize

### ISSUE THREAD

**Issue by Mygod** [WatWowMap/Chuck#16]
Leftover issue from #2.

Currently sequelize scheme does not support generated column, which is used by MapJS (notably used for quest filtering etc). We should either update MapJS to stop using them, or put it there in the migration script.

**Comment by versx** [comment]
Generated column as in a `virtual` column? Sequelize supports this.

**Comment by Mygod** [comment]
[Manual] says:

> Virtual fields are fields that Sequelize populates under the hood, but in reality they don't even exist in the database.

In particular, it will not be visible to other projects like MapJS.

Related issue: https://github.com/sequelize/sequelize/issues/11123

**Comment by versx** [comment]
Right I understand it being project related and implementing it as a virtual/generated column. Why not add the generation to the table schema like RDM uses?

**Comment by Mygod** [comment]
That's the point of this issue.

**Comment by versx** [comment]
Isn't it already in the schema?
https://github.com/WatWowMap/Chuck/blob/master/migrations/1.sql#L216
https://github.com/WatWowMap/Chuck/blob/master/migrations/1.sql#L164

**Comment by Mygod** [comment]
It's not in sequelize schema so if we want automatic migrations, we would have problems.

**Comment by versx** [comment]
If we add them as virtual columns we should be fine though right?

**Comment by Mygod** [comment]
As I pointed above, 1 no and 2 I'd rather not have unused code.

**Comment by matwaroff** [comment]
@Mygod Was this ever implemented? I don't see any updates in the #19 PR that would address this
